### ISSUE TITLE
NoMethodError: undefined method `parser=' for Nori:Class

### ISSUE THREAD

**Issue by vpereira** [openSUSE/rubygem-zypper#1]
https://github.com/openSUSE/rubygem-zypper/blob/master/lib/zypper/utils.rb#L31

```
2.1.1 :001 > require 'zypper'
NoMethodError: undefined method `parser=' for Nori:Class
    from /home/vpereira/.rvm/gems/ruby-2.1.1/gems/zypper-0.3.0/lib/zypper/utils.rb:31:in `<module:ZypperUtils>'
    from /home/vpereira/.rvm/gems/ruby-2.1.1/gems/zypper-0.3.0/lib/zypper/utils.rb:1:in `<top (required)>'
    from /home/vpereira/.rvm/rubies/ruby-2.1.1/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/vpereira/.rvm/rubies/ruby-2.1.1/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/vpereira/.rvm/gems/ruby-2.1.1/gems/zypper-0.3.0/lib/zypper.rb:1:in `<top (required)>'
    from /home/vpereira/.rvm/rubies/ruby-2.1.1/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /home/vpereira/.rvm/rubies/ruby-2.1.1/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /home/vpereira/.rvm/rubies/ruby-2.1.1/lib64/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from (irb):1
    from /home/vpereira/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'
2.1.1 :003 > 
```

**Comment by vpereira** [comment]
with `gem install zypper` , it was installed the nori (2.6.0)

Zypper needs nori 1.1.0.. you should lock it somehow..

**Comment by vpereira** [comment]
https://github.com/openSUSE/rubygem-zypper/pull/2 fixes it
